# Generated by Django 2.1.2 on 2019-04-23 17:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Patient', '0009_auto_20190423_2236'),
        ('Labtechnician', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Make_labreport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_result', models.CharField(max_length=50)),
                ('patient_appointment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Patient.Patient_appointment')),
                ('test_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Labtechnician.Add_test')),
            ],
        ),
    ]
