# Generated by Django 2.1.2 on 2019-04-23 17:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Patient', '0009_auto_20190423_2236'),
        ('Labtechnician', '0002_make_labreport'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prescribed_test',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ptest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Patient.Patient_appointment')),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Labtechnician.Add_test')),
            ],
        ),
    ]
