# Generated by Django 2.1.2 on 2019-04-20 09:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Doctor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient_appointment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disease', models.TextField()),
                ('date', models.DateField()),
                ('status', models.CharField(blank=True, choices=[('Confirmed', 'Confirmed'), ('Pending', 'Pending')], default='Pending', max_length=25, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Patient_profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=10)),
                ('address', models.TextField()),
                ('mobile', models.IntegerField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='patient_appointment',
            name='patient_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Patient.Patient_profile'),
        ),
        migrations.AddField(
            model_name='patient_appointment',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Doctor.Profile'),
        ),
    ]
