# Generated by Django 2.1.2 on 2019-04-21 11:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Pharmist', '0002_auto_20190420_1611'),
        ('Patient', '0002_prescribed_medicine'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescribed_medicine',
            name='drugs',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Pharmist.Drugs'),
            preserve_default=False,
        ),
    ]
