# Generated by Django 2.1.2 on 2019-04-21 12:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Patient', '0003_prescribed_medicine_drugs'),
    ]

    operations = [
        migrations.RenameField(
            model_name='prescribed_medicine',
            old_name='drugs',
            new_name='pdrugs',
        ),
    ]
