# Generated by Django 2.1.2 on 2019-04-22 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Patient', '0004_auto_20190421_1737'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescribed_medicine',
            name='afternoon',
            field=models.CharField(choices=[('Before Meal', 'Before Meal'), ('After Meal', 'After Meal'), ('Fasting', 'Fasting')], default=1, max_length=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='prescribed_medicine',
            name='evening',
            field=models.CharField(choices=[('Before Meal', 'Before Meal'), ('After Meal', 'After Meal'), ('Fasting', 'Fasting')], default=1, max_length=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='prescribed_medicine',
            name='morning',
            field=models.CharField(choices=[('Before Meal', 'Before Meal'), ('After Meal', 'After Meal'), ('Fasting', 'Fasting')], default=1, max_length=15),
            preserve_default=False,
        ),
    ]
