# Generated by Django 2.1.2 on 2019-04-22 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Patient', '0005_auto_20190422_0738'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prescribed_medicine',
            name='afternoon',
            field=models.CharField(choices=[('X', 'X'), ('Before Meal', 'Before Meal'), ('After Meal', 'After Meal'), ('Fasting', 'Fasting')], max_length=15),
        ),
        migrations.AlterField(
            model_name='prescribed_medicine',
            name='evening',
            field=models.CharField(choices=[('X', 'X'), ('Before Meal', 'Before Meal'), ('After Meal', 'After Meal'), ('Fasting', 'Fasting')], max_length=15),
        ),
        migrations.AlterField(
            model_name='prescribed_medicine',
            name='morning',
            field=models.CharField(choices=[('X', 'X'), ('Before Meal', 'Before Meal'), ('After Meal', 'After Meal'), ('Fasting', 'Fasting')], max_length=15),
        ),
    ]
