# Generated by Django 2.1.2 on 2019-04-22 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Patient', '0006_auto_20190422_0742'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescribed_medicine',
            name='units',
            field=models.IntegerField(default=500),
            preserve_default=False,
        ),
    ]
