# Generated by Django 2.1.2 on 2019-04-22 09:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Patient', '0007_prescribed_medicine_units'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient_appointment',
            name='date',
            field=models.DateField(default=datetime.datetime(2019, 4, 22, 15, 9, 4, 157661)),
        ),
    ]
