# Generated by Django 2.1.2 on 2019-04-23 17:06

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Patient', '0008_auto_20190422_1509'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient_appointment',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
