# Generated by Django 2.1.2 on 2019-04-26 12:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Patient', '0009_auto_20190423_2236'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sale', models.BooleanField(default=False)),
                ('drugsname', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Patient.Prescribed_medicine')),
            ],
        ),
        migrations.AlterField(
            model_name='patient_profile',
            name='address',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='patient_profile',
            name='mobile',
            field=models.IntegerField(default='0'),
        ),
    ]
