# Generated by Django 2.1.2 on 2019-04-20 09:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Doctor', '0001_initial'),
        ('Patient', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='add_Pharmist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('address', models.TextField()),
                ('email', models.EmailField(max_length=254)),
                ('degree', models.CharField(choices=[('1', 'D.pharma'), ('2', 'B.pharma'), ('3', 'M.pharma'), ('4', 'B.Ayurvedic')], max_length=4)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Drugs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Brand_Name', models.CharField(max_length=50)),
                ('Unit', models.IntegerField()),
                ('Active_ingredients', models.CharField(max_length=50)),
                ('price', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Prescribed_medicine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Patient.Patient_profile')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Doctor.Profile')),
            ],
        ),
    ]
