# Generated by Django 2.1.2 on 2019-04-20 10:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Pharmist', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prescribed_medicine',
            name='patient_profile',
        ),
        migrations.RemoveField(
            model_name='prescribed_medicine',
            name='profile',
        ),
        migrations.DeleteModel(
            name='Prescribed_medicine',
        ),
    ]
