# Generated by Django 2.1.2 on 2019-04-20 09:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.TextField(max_length=500)),
                ('speciality', models.CharField(max_length=50)),
                ('degree', models.CharField(choices=[('MB', 'MBBS( Bachelor of Medicine, Bachelor of Surgery)'), ('BDS', 'BDS(Bachelor of Dental Surgery)'), ('BAMS', 'BAMS( Bachelor of Ayurvedic Medicine and Surgery)'), ('BUMS', 'BUMS(Bachelor of Unani Medicine and Surgery)'), ('BHMS ', 'BHMS( Bachelor of Homeopathy Medicine and Surgery)'), ('MD', 'MD(Doctor of Medicine)'), ('MS', 'MS(Masters of Surgery)'), ('DNB', 'DNB(Diplomate of National Board )')], max_length=8)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('Experience', models.CharField(choices=[('0', '0 Years'), ('1', '1 Years'), ('2', '2 Years'), ('3', '3 Years'), ('4', '4 Years'), ('5', '5 Years'), ('6', '6 Years')], max_length=7)),
                ('department', models.CharField(choices=[('1', 'Dental'), ('2', 'Ophthalmology'), ('3', 'Cardiology'), ('4', 'For Disabled'), ('5', 'Emergency')], max_length=45)),
                ('fees', models.IntegerField(null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
