# Generated by Django 2.1.2 on 2019-04-22 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Doctor', '0002_auto_20190420_1704'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='department',
            field=models.CharField(choices=[('Dental', 'Dental'), ('Ophthalmology', 'Ophthalmology'), ('Cardiology', 'Cardiology'), ('For Disabled', 'For Disabled'), ('Emergency', 'Emergency')], max_length=45),
        ),
    ]
