# Generated by Django 2.1.7 on 2019-04-25 15:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Patient', '0009_auto_20190423_2236'),
        ('Labtechnician', '0003_prescribed_test'),
        ('Receptionist', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appointmentbill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Patient.Patient_appointment')),
                ('medicine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Patient.Prescribed_medicine')),
                ('tests', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Labtechnician.Prescribed_test')),
            ],
        ),
    ]
